### ISSUE TITLE
Manage error for outdated format of GTFS dataset

### ISSUE THREAD

**Issue by bordoray** [MIERUNE/GTFS-GO#56]
Old GTFS dataset doesn't work, and process still running endlessly.
It may be due to a lack of required file(s) in current standardized GTFS format.

It would be nice to have a GTFS format checker, which throw an error if file(s) is or are missing.

Examples of unworking dataset:
- https://transitfeeds.com/p/ile-de-france-mobilite/1214
- https://transitfeeds.com/p/regie-autonome-des-transports-parisiens/413/latest
- https://transitfeeds.com/p/stif/822/latest

**Comment by takohei** [comment]
All sample feeds are missing feed_info.txt.
We fixed on v3.2.3 by PR #76
@Kanahiro Please close this issue.

https://transitfeeds.com/p/ile-de-france-mobilite/1214
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/03b2128e-bdba-4462-8dca-4d722b0776fe)
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/fcb5ea79-da27-4953-8a80-d520faa22d77)

https://transitfeeds.com/p/regie-autonome-des-transports-parisiens/413/latest
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/e910ca1a-6231-43a0-a058-5ba0868c596e)
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/e4bf8e37-3102-4523-a532-f39df2ba2c12)

https://transitfeeds.com/p/stif/822/latest
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/5b94f6e7-d38c-487a-8979-da4dddb65122)
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/e7807612-39a9-45da-bc45-f4d3606c9eae)

**Comment by Kanahiro** [comment]
thanks, close...
