### ISSUE TITLE
Chaos on Vancouver, Canada GTFS dataset

### ISSUE THREAD

**Issue by Highfire1** [MIERUNE/GTFS-GO#77]
Hi, really awesome plugin!

Something goes wrong with the shapes.txt on the GTFS dataset for vancouver (https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/gtfs/gtfs-data), and I'm not sure why as the sequence numbers in the dataset seem to be correct.

![image](https://github.com/MIERUNE/GTFS-GO/assets/45698812/4c5638bc-f015-475f-9eec-45422232a42b)

![image](https://github.com/MIERUNE/GTFS-GO/assets/45698812/19241c61-3aed-4da9-86d5-5c6c867c9a1d)

Using QGIS version 3.34.2 and plugin version 3.2.2

Thanks!

**Comment by Kanahiro** [comment]
thank you for reporting! I'll check them...

**Comment by takohei** [comment]
I fixed this problem by PRs.
* #81 
* MIERUNE/gtfs-parser#11 

**routes without shapes**
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/7dbf6a48-2f53-49ad-a2e7-c10b36714ad6)

**routes with shapes**
![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/365b27f5-9abf-48c8-bff3-c2783f020b42)

**Comment by Kanahiro** [comment]
Fixed!

![Screenshot 2024-05-08 at 16 54 17](https://github.com/MIERUNE/GTFS-GO/assets/20744195/e9c73adf-22fc-4703-b6fa-347199dbec99)

**Comment by Kanahiro** [comment]
![Screenshot 2024-05-08 at 16 55 01](https://github.com/MIERUNE/GTFS-GO/assets/20744195/3bf7ae29-7b0f-49f8-8500-0f8d0d6794c5)

**Comment by Kanahiro** [comment]
@Highfire1 
You will be able to handle this issue from `v4.0.0` comming soon.
